name: ldsc
channels:
  - bioconda
dependencies:
  - python=3.9
  - pip
  - pip:
      - bitarray==2
      - nose==1.3
      - pybedtools==0.10.0
      - scipy==1.7.3
      - pandas==1.3.3
      - numpy==1.21.5
