name: ldsc
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - python=2.7
  - bitarray=2
  - nose=1.3
  - pybedtools=0.10.0
  - scipy=1.7.3
  - pandas=1.3.3
  - numpy=1.21.2
  - parse=1.20.2
