name: ldsc
channels:
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - bitarray=2
  - nose=1.3
  - pybedtools=0.10.0
  - pip
  - flask
  - requests
  - nose=1.3
  - pip:
      - numpy==1.21.5
      - pandas==1.3.3
      - scipy==1.7.3